### ISSUE TITLE
Support for methods

### ISSUE THREAD

**Issue by fccoelho** [google/latexify_py#105]
## Description

I would like to be able to latexify class(instance) methods such as this simple example:
```python
class Test:
    @latexify.function
    def fun(self,a,b):
        return a+b
T = Test()
T.fun
```
this simple example does not work on 0.2.0b2

**Comment by odashi** [comment]
@fccoelho Thanks!
Would the expected output be: $\mathrm{fun}(a, b) = a + b$, or something else?

**Comment by odashi** [comment]
I think the code above does show something:

<img width="586" alt="スクリーンショット 2022-11-15 062403" src="https://user-images.githubusercontent.com/1023695/201768578-389e766d-df5d-4ff8-a505-a2b210ef30ae.png">

The first case is correct, while the second/third cases should be `fun(a, b)` according to its actual signature

**Comment by fccoelho** [comment]
I guess I was just missing the use of the `display` function. Thanks @odashi

**Comment by odashi** [comment]
@fccoelho I'd appreciate it if I could help!

Btw, supporting bound functions (2nd/3rd cases of above) is not easy because latexify couldn't know how the wrapped functions are used *after wrapping them*. I'd close this issue for now, and would come back here when this issue gets more attention.
