### ISSUE TITLE
underscores in variable names not displaying correctly

### ISSUE THREAD

**Issue by ontocord** [google/latexify_py#106]
@latexify.function
def solve(a_a, b, c):
  return (-b + math.sqrt(b**2 - 4*a_a*c)) / (2*a_a)

solve  # Display the MathJax.

Will produce the variable a, with the next a as a subscript, instead of displaying the underscore.

**Comment by odashi** [comment]
@ontocord Thanks for reporting! This problem is currently tracked by #82.
