### ISSUE TITLE
latexify.function doesn't work with ptpython

### ISSUE THREAD

**Issue by Freed-Wu** [google/latexify_py#129]
## Environment

If you used latexify on the browser, fill the following items.

* Browser: 
* Frontend: 

If you used latexify in your own environment, fill at least the following items.
Feel free to add other items if you think they are useful.

* OS: linux 6.0.8-arch1-1
* Python: 3.10.8
* Package manager: pacman
* Latexify version: 0.2.0

## Description

Describe the details of the issue. Feel free to insert screenshots if they are useful.

## Reproduction

Describe how to reproduce the issue by other people.

```python
In [14]: import math
       2 import latexify
       3
       4 @latexify.function
       5 def solve(a, b, c):
       6     return (-b + math.sqrt(b**2 - 4 * a * c)) / (2 * a)
In [15]: latexify.get_latex(solve)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wzy/.local/lib/python3.10/site-packages/latexify/frontend.py", line 51, in get_latex
    tree = parser.parse_function(fn)
  File "/home/wzy/.local/lib/python3.10/site-packages/latexify/parser.py", line 36, in parse_function
    raise exceptions.LatexifySyntaxError("Not a function.")
latexify.exceptions.LatexifySyntaxError: Not a function.

Not a function.
```

## Expected behavior

Describe how latexify should behave in the case above.

As example.

**Comment by odashi** [comment]
@Freed-Wu Hi, it looks you tried to invoke `latexify.get_latex` with an already wrapped function by `latexify.function`.

Please try either 1. or 2. as follows:

1. `str(solve)` instead of `latexify.get_latex(solve)`.
2. Remove the `@latexify.function` wrapper, then `latexify.get_latex(solve)`.

**Comment by odashi** [comment]
And I noticed that maybe the library need to return the argument itself if it is already wrapped. Thanks for reporting!

**Comment by Freed-Wu** [comment]
Nothing changes.

```python
In [1]: import math
      2 import latexify
      3
      4 @latexify.function
      5 def solve(a, b, c):
      6     return (-b + math.sqrt(b**2 - 4 * a * c)) / (2 * a)
In [2]: str(solve)
Out[2]: "LatexifySyntaxError: Not a function."

In [3]: import math
      2 import latexify
      3
      4 def solve(a, b, c):
      5     return (-b + math.sqrt(b**2 - 4 * a * c)) / (2 * a)
In [4]: latexify.get_latex(solve)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/latexify/frontend.py", line 51, in get_latex
    tree = parser.parse_function(fn)
  File "/usr/lib/python3.10/site-packages/latexify/parser.py", line 36, in parse_function
    raise exceptions.LatexifySyntaxError("Not a function.")
latexify.exceptions.LatexifySyntaxError: Not a function.

Not a function.
In [4]:
```

**Comment by odashi** [comment]
@Freed-Wu What kind of CLI are you using? If the comment above does not solve the problem, it may be the problem related to the console you are using, and I need to know more about your environment.

**Comment by Freed-Wu** [comment]
I use [ptpython](https://github.com/prompt-toolkit/ptpython/). I have tested and found it can work in `python` but not work in `ptpython`

**Comment by odashi** [comment]
Great, I will check what happens with it.

**Comment by odashi** [comment]
I tried `ptpython` on my machine. It looks the console hides the original source, or does not store the input code as a source.
```
>>> def f(x):
...     return x
>>> import inspect
>>> inspect.getsource(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/inspect.py", line 1147, in getsource
    lines, lnum = getsourcelines(object)
  File "/usr/lib/python3.10/inspect.py", line 1129, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/lib/python3.10/inspect.py", line 958, in findsource
    raise OSError('could not get source code')
OSError: could not get source code

could not get source code
>>> import dill
>>> dill.source.getsource(f)
'#!/home/me/mydir/venv/bin/python\n'

>>> print(' '.join(dill.source.findsource(f)[0]))
#!/home/me/mydir/venv/bin/python
 # -*- coding: utf-8 -*-
 import re
 import sys
 from ptpython.entry_points.run_ptpython import run
 if __name__ == '__main__':
     sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
     sys.exit(run())

>>>
```

I also tried it on `ipython` to check if there's some related issues, but it still works:
```
In [1]: import latexify

In [2]: def f(x):
   ...:     return x
   ...: 

In [3]: latexify.get_latex(f)
Out[3]: '\\mathrm{f}(x) = x'

In [4]: 
```

So it turns that the problem comes from something in `ptpython`. I guess it'd be better to report this behavior to their issue tracker.

**Comment by Freed-Wu** [comment]
As a compleiton, it can work for ptipython (provided by ptpython).

**Comment by odashi** [comment]
Great! I also tried it and observed it works.

```
(venv) ~/mydir $ ptipython
Python 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.6.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import latexify

In [2]: def f(x):
   ...:     return x

In [3]: latexify.get_latex(f)
Out[3]: '\\mathrm{f}(x) = x'
```
