### ISSUE TITLE
Custom multiplication behavior (option to use \cdot everywhere)

### ISSUE THREAD

**Issue by ZibingZhang** [google/latexify_py#156]
## Description

The current behavior of multiplication is as follows

```python
>>> def f(x):
    return 3 * 5 * x
>>> latexify.get_latex(f)
f(x) = 3 5 x
```

I personally like having `\cdot`, and there are other options for multiplication as well: `\times`, `*`, etc.

I think we should support specifying the multiplication operator due to the number of options.

## Ideas of the solution

Add it as a config option.

**Comment by odashi** [comment]
#89 was accidentally closed, but this issue should be a part of it.
