### ISSUE TITLE
Should `def(x): func(x)` generate `\func x` or `\func \mathopen{}\left( x \mathclose{}\right)`?

### ISSUE THREAD

**Issue by ZibingZhang** [google/latexify_py#157]
## Description

Should `def(x): sum(x)` generate `\sum x` or `\sum \mathopen{}\left( x \mathclose{}\right)`?

I personally feel like parentheses should not be dropped by default, and should be an option to drop parens for functions with basic arguments, e.g. `sin(x) -> \sin x`.

Or maybe they're only dropped by default for these builtin functions?

**Comment by Casper-Guo** [comment]
In this specific case, I think $\sum x$ is more desirable since that's the more standard notation

**Comment by ZibingZhang** [comment]
Lol I forgot `\sum` was a symbol, closing this issue out because it's a non-issue...
