### ISSUE TITLE
Please add support for Python >3.11

### ISSUE THREAD

**Issue by Rene19700107** [google/latexify_py#175]
## Description

Is your feature request related to a problem? Please describe it.
A clear and concise description is recommended to proceed the discussion efficiently.

## Ideas of the solution

If you have an idea about the solution you'd like, describe details about it.

## Alternative ideas

If you have other ideas that are already considered, describe them as well.
These ideas may also help us to make reasonable decisions.

**Comment by odashi** [comment]
The main branch already supports 3.11, but it hasn't been released. You can install the repository directly, or please wait for the new release. (Apologizing that I'm busy in the main job now, and it may be delayed)

**Comment by odashi** [comment]
Fixed in v0.3.1 that supports 3.11. (though this issue is named "> 3.11", it doesn't mean ">= 3.12" I think)
