### ISSUE TITLE
Better Identifier For Multi Index and RHS

### ISSUE THREAD

**Issue by yasirroni** [google/latexify_py#177]
## Environment

If you used latexify in your own environment, fill at least the following items.
Feel free to add other items if you think they are useful.

* OS: Windows 10
* Python: 3.8
* Package manager: pip 22.3.1
* Latexify version: 0.2.0

## Description

```
identifiers = {
    "D11": "D_\{1,1\}",
    "central_diff": "central\_diff",
}

@latexify.function(identifiers=identifiers)
def D11(f, h, x):
    return (4/3)*central_diff(f,h/2,x) - (1/3)*central_diff(f,h,x)
display(D11)
```

## Reproduction

```
identifiers = {
    "D11": "D_\{1,1\}",
    "central_diff": "central\_diff",
}

@latexify.function(identifiers=identifiers)
def D11(f, h, x):
    return (4/3)*central_diff(f,h/2,x) - (1/3)*central_diff(f,h,x)
display(D11)
```

## Expected behavior

Identifiers seems very limited and can't be used to express underscore freely. Also no support for multiple index and literal underscore.

I hope that I'm able to write something like this:

$$
D_{1,1}(f, h, x)= \frac{4}{3} \text{central<underscore>diff}(f, h/2, x) - \frac{1}{3} \text{central<underscore>diff}(f,h,x)
$$

**Comment by odashi** [comment]
@yasirroni Thanks for the report. Yeah this is somewhat not intuitive, and I also think it is more desirable if we can use arbitrary LaTeX expression in `identifiers`.

In the current implementation, `identifiers` are applied *before* staring LaTeX conversion. That means both key/value of `identifiers` are used as a part of Python AST, and the replaced names will be processed by the same routines. I think we should introduce some trick to bypass this conversion (e.g., adding a flag "already converted" to replaced nodes).

**Comment by odashi** [comment]
Note that the newest version v0.3.1 keeps underscores in the identifier as-is:
<img width="505" alt="無題" src="https://github.com/google/latexify_py/assets/1023695/41611c48-dcd4-44a7-a195-ac912057a908">

**Comment by yasirroni** [comment]
I will try to look at it and give feedback here.

**Comment by odashi** [comment]
I close this for now, feel free to put additional comments if you realized something relevant.
