### ISSUE TITLE
Can you sub in values for show work?

### ISSUE THREAD

**Issue by aeslaughter** [google/latexify_py#178]
Is it possible to "show your work"? For example something like the following or as done in the `latexexpr` package (http://mech.fsv.cvut.cz/~stransky/en/software/latexexpr/)

```
@latexify.function
def add(a, b, c):
  return a + b + c
```

add.show_work(1,2,3)
```
\mathrm{add}(a, b, c) = a + b + c = 1 + 2 + 3 = 6 
```

**Comment by odashi** [comment]
Generating derivation is interesting, but IMO it is probably beyond the scope of this library. latexify aims to generate LaTeX outputs without breaking most of the original representation, and employs no any calculation on the target functions.
latexify also aims to support any algorithms (especially with `@latexify.algorithmic`), and I guess it is not very intuitive to determine the reasonable form of derivations.

Probably it is better to develop a separate library that works friendly with latexify?
