### ISSUE TITLE
Release New Version

### ISSUE THREAD

**Issue by martinvonk** [google/latexify_py#180]
Hi @odashi,

Thank you for this nice python package. Our Python package [Pastas](https://github.com/pastas/pastas) that uses your package needs a new release of Latexify to fully support Python 3.11. Is it possible to release a new version in the near future?

Thank you in advance!

**Comment by odashi** [comment]
Yeah definitely, sorry for inconvenience due to recent inactivity.
Though full functionality is not implemented for the next release, I think the main is stable and it would be better to release it soon. I have no time to do this on weekdays and will try it in this or next weekend.

**Comment by jianan1104** [comment]
@odashi Is there anything can help?

**Comment by odashi** [comment]
@jianan1104 Thanks for your support!

Well, there is not actually many tasks to release the new version and I could do it if I just decided so.
The largest problem is the match support (#158 and some discussions), but I think it is much better to make an intermediate release without full support of it.

**Comment by odashi** [comment]
I just created a pre-release: [v0.3.0b1](https://github.com/google/latexify_py/tree/v0.3.0b1).
It is currently available on PyPI as well with manually specifying the version.
I will make the actual release after checking if several functionality works.

**Comment by odashi** [comment]
It turns out that we should implement at least #89 because for better compatibility, applied #182.

**Comment by odashi** [comment]
Released [v0.3.1](https://github.com/google/latexify_py/releases/tag/v0.3.1).
