### ISSUE TITLE
Support for log1p and expm1?

### ISSUE THREAD

**Issue by jonbarron** [google/latexify_py#185]
## Description

It would be great to have support for `np.log1p()` and `np.expm1()`.

## Ideas of the solution

It seems like a preprocessing step that replaces `log1p(...)` with `log(1 + ...)` and `expm1(...)` with `(exp(...)-1)` would be sufficient.

## Additional context

<img width="419" alt="image" src="https://github.com/google/latexify_py/assets/889526/f807ec69-aff7-41ef-9400-1de1151b5a97">

**Comment by odashi** [comment]
I think `expand_functions` should work. Some functions are registered with its expanded forms (though this feature is not documented enough...)

<img width="444" alt="タイトルなし" src="https://github.com/google/latexify_py/assets/1023695/02714170-85c8-4ea8-9d2a-aa395d2f11d1">

**Comment by odashi** [comment]
Old discussion: #65

Possibly there is also another question: whether we should treat this behavior as default or not

**Comment by jonbarron** [comment]
thank you!

**Comment by jonbarron** [comment]
and yeah I think having this be default for expm1 and log1p makes sense, I can't imagine many contexts where someone wouldn't want these to be expanded out. I'm less sure about functions like atan2. But yeah just having this be better documented is probably the easiest path forward.
