### ISSUE TITLE
Typo in \mathopen

### ISSUE THREAD

**Issue by jonbarron** [google/latexify_py#187]
It looks like abs() is broken because `\mathopen` is misspelled there. Am I understanding this correctly?

https://github.com/google/latexify_py/blob/e0ddde4ed19beb61179562930b1c05ca8a313398/src/latexify/codegen/expression_rules.py#L218

**Comment by odashi** [comment]
Thanks for reporting the bug. Could you propose a pull request so that I can simply merge the changes to fix it?

**Comment by jonbarron** [comment]
Hah sadly no, I don't really know how to use github!

**Comment by jonbarron** [comment]
okay I might have submitted a PR for review, I'm bad enough at github that I don't know if I did it right. https://github.com/google/latexify_py/pull/188
