### ISSUE TITLE
Non working link on the pypi page of the project

### ISSUE THREAD

**Issue by quark67** [google/latexify_py#203]
## Environment

If you used latexify on the browser, fill the following items.

* Browser: n/a
* Frontend: n/a

## Description

On https://pypi.org/project/latexify-py/, the link to the official documentation (https://pypi.org/project/latexify-py/docs/index.md) isn't working (Error code: 404, page not found).

<img width="673" alt="image" src="https://github.com/google/latexify_py/assets/9338576/304d4975-d6f7-4421-854c-276f75a6a5b6">

This page (https://pypi.org/project/latexify-py/) has also a missing image:

<img width="781" alt="image" src="https://github.com/google/latexify_py/assets/9338576/b235af6a-093f-48c0-bc44-09d3e23ddd4b">

The missing image is:

![image](https://github.com/google/latexify_py/assets/9338576/c2afd937-aefc-4d15-9b0e-2255562d934d)

(image hosted at https://github.com/google/latexify_py/blob/main/example.jpg).

These errors are probably because because the .md file used at https://pypi.org/project/latexify-py/ contain relative URLs from the GitHub .md file, not the absolute URLs.

## Reproduction

Go to the page https://pypi.org/project/latexify-py/ with your browser.

## Expected behavior

Access to the official documentation (at https://github.com/google/latexify_py/blob/main/docs/index.md or at https://pypi.org/project/latexify-py/docs/index.md if the `index.md` file is hosted at https://pypi.org) and see the image example (yet hosted at https://github.com/google/latexify_py/blob/main/example.jpg).

**Comment by odashi** [comment]
@quark67 Thanks! I will update the documentation correctly.

**Comment by odashi** [comment]
`v0.4.3` (and `v0.4.3-post1`) reflected the change.
