### ISSUE TITLE
Similar to handcalcs?

### ISSUE THREAD

**Issue by connorferster** [google/latexify_py#25]
Hi folks,

It seems we have similar projects! :smile:

https://github.com/connorferster/handcalcs

**Comment by 1MLightyears** [comment]
hmmmm... 
I have to say they have some similar functions, but are implemented in totally different approaches and used in no situations in common at all.

**Comment by odashi** [comment]
Hi, thanks to notifying!

Yes I knew your project (which is quite nice 😃 ). I understood that is oriented for scratching math on Jupyter, using Python as a "math language."

This project is in contrast oriented to generate LaTeX from usual Python code which are possibly written already somewhere, with keeping (most) original functionality.

These are developed for different use-cases I guess, but the functionality on Jupyter is somewhat similar.

**Comment by connorferster** [comment]
Thanks! I like Latexify-py, too. I plugged it on a Reddit thread last week.

handcalcs also has a function decorator interface to be used in non-Jupyter environments. I think the key difference is that Latexify-py is more focussed on theoretically representing the whole body of a function symbolically whereas handcalcs is focussed primarily on tracing computation by a) only rendering the happy path through branched conditionals and b) by showing all numeric substitutions to the symbolic form.

Plus, Latexify-py has more sophisticated code by working directly on the ast (~200 lines of code: amazing!). handcalcs is over 2000 lines of code and is operating on nested lists generated from pyparsing.

**Comment by odashi** [comment]
Yeah that's the point!

I also guess we can possibly have some cooperation on similar functionalities. I am roughly thinking of separating LaTeX code generator and its printer on Jupyter from the current AST parser to increase portability. It may be worthy for other tools relying on LaTeX too. (ironically it may increase LOCs from 200 🙃 )

**Comment by odashi** [comment]
This is a general discussion, would like to close it for now.
