### ISSUE TITLE
Limits in Summations

### ISSUE THREAD

**Issue by shivam-kotwalia** [google/latexify_py#30]
Hello Team - thanks for this wonderful package, I was wondering how do we put a limit on summation. 
![image](https://user-images.githubusercontent.com/14539580/94681234-b5ee0f80-0340-11eb-9ec7-166d8b4eb6d2.png)

Thanks in advance :)

**Comment by odashi** [comment]
It is not supported for now. I guess some special treatment is needed for analyzing `sum()`.

E.g., the following expression:

```python
sum((y_bar[i] - y[i])**2 for i in range(n))
```

would represent your case, though it needs a deeper traverse over AST.

Yes it is doable, please wait a while to discuss it internally (or your PR is also welcome!)
