### ISSUE TITLE
Underscores in function names conflict with LaTeX and shown as subscripts

### ISSUE THREAD

**Issue by ryosuketc** [google/latexify_py#31]
Underscores in function names conflict with LaTeX and thus it is represented as subscript in LaTeX.

![image](https://user-images.githubusercontent.com/43229670/95415851-54472a00-096c-11eb-8e86-c519f61d90a9.png)

In Jupyter Notebook:
```python
@latexify.with_latex
def func_with_underscore(x):
  return 1

func_with_underscore
```

**Comment by odashi** [comment]
Yeah the underscores in identifiers should be escaped normally, but in some few cases they are worthy for special treatment (as #6 discussed).

**Comment by 1MLightyears** [comment]
It looks like only "_" the underline is the only character that has the problem
See if I could fix it 🤔

**Comment by yasirroni** [comment]
For those that come here and confused to implement it:

```
@latexify.with_latex(use_raw_function_name=True)
def forward_diff(f, h, x):
    return f(x + h) / h
```

See https://github.com/google/latexify_py/issues/82
