### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement latexify-py (from versions: none)

### ISSUE THREAD

**Issue by rampallishyam** [google/latexify_py#37]
I am using Windows 11 and I have python 3.9.11 installed on my laptop. I for this error when I used the code `pip install latexify-py`
Please help.

**Comment by zhangzaixuan** [comment]
I need it,but I am on a version with 3.9,it's so bad

**Comment by odashi** [comment]
Now the released version (v0.1.1) supports versions up to v3.10.
