### ISSUE TITLE
Support for Numpy or PyTorch or TF

### ISSUE THREAD

**Issue by imflash217** [google/latexify_py#38]
Hi,
Very nice tool. Thanks a lot. I was just wondering if there will be any support for libraries like NumPy, PyTorch or TensorFlow?

**Comment by odashi** [comment]
I think there are several levels to support NumPy-like libraries:

1. Support function signatures
2. Support array visualization

A recent change #49 adds support for several functions in NumPy.
I'm also thinking of whether it is good to provide some support for array visualization too, but it is not trivial and sometimes we couldn't get shape information before running the function.

**Comment by odashi** [comment]
Some features are taken over by other issues. Close this issue for now.
