### ISSUE TITLE
Support for nested functions

### ISSUE THREAD

**Issue by alecglen** [google/latexify_py#46]
As an example use case, I have a function that takes in a dataset and returns a closure based on that dataset.
```python
def gen_normalizer(df):

    def normalize_row_based_on_dataset(row):
        return (row - df.mean()) / df.std()
    
    return normalize_row_based_on_dataset
```

I would love to be able to apply the decorator to the nested function so that later in my experiment I can display a set of different Normalizers in LaTeX. However, currently adding the decorator to the nested function results in the following error:
```python
File <unknown>:1
    @latexify.with_latex
    ^
IndentationError: unexpected indent
```

**Comment by odashi** [comment]
Thanks for reporting the issue!

The cause of this is that all lines of the inner function have extra indentation. I think `dedent`-ing the obtained source before parsing may solve the problem.

<img width="413" src="https://user-images.githubusercontent.com/1023695/194513943-5c6e5ebd-4fb8-4ca8-846f-d4c1e52dc2fa.png">

**Comment by alecglen** [comment]
Thank you for the quick turnaround! When do you expect to release v0.2?

**Comment by odashi** [comment]
Yes, if you want to try it out soon, please install the trunk directly or apply the same changes.

**Comment by alecglen** [comment]
Fair, thanks again!

As a followup, part of my goal in the example above was for the latex equation to display the literal values for `df.mean()` and `df.std()`. In hindsight, I see now why that doesn't work naturally and that it might not even be possible.

Figured it doesn't hurt to ask anyway, though... Is there any way to coerce latexify into computing certain values so their literal value shows in the final expression? E.g. getting 5 and 2 in this simplified example:

![image](https://user-images.githubusercontent.com/28493454/195731819-565ea4cd-05f3-4303-98cb-9aafbccb7d8d.png)

**Comment by odashi** [comment]
@alecglen I will create another issue, thanks!
