### ISSUE TITLE
Setting one directory for all test scripts

### ISSUE THREAD

**Issue by hirwa-nshuti** [google/latexify_py#48]
I would like to suggest that you can make one directory outside the source code directory to hold all testing scripts this might be helpful even when the codebase grows. If this is acceptable I am open to helping restructure it.
Thanks:)

**Comment by odashi** [comment]
@hirwa-nshuti Hi, thanks for proposing this issue.

Several days ago, I restructured the repository to:

- Put all unit tests beside the source, and
- Put other tests to `src/integration_tests`

I think this is practical to find corresponding unit tests easily, and allows us to efficiently organize the whole repository (e.g., if we realized some necessity of further restructuring, we need to take care about only one directory tree)
I have also worked with this kind of structures in some large repositories.

**Comment by hirwa-nshuti** [comment]
Makes sense thanks:)
