### ISSUE TITLE
Ability to get latex without getting function name

### ISSUE THREAD

**Issue by MAKMED1337** [google/latexify_py#54]
```
import latexify
def solve(a):
	return 5 * a
print(latexify.get_latex(solve, no_function=True))
```
to be `5a`, not `\mathrm{solve}(a) \triangleq 5a`

i think it's better to create another function not parameter or set by default

**Comment by odashi** [comment]
Using `latexify.expression` or something similar would be good. I also guess that the current function names `with_latex` and `get_latex` is weird a little; possibly we can redefine it as `latexify.equation` (but we also need to keep the current functions for a while, for backward compatibility).
