### ISSUE TITLE
How to use latexify for scipy.special.expit ?

### ISSUE THREAD

**Issue by Vector-Cross** [google/latexify_py#63]
I want to latexify scipy.special.expit In jupyter lab. 
What should I do?
![image](https://user-images.githubusercontent.com/36829977/197439466-d1780e8e-5fe1-46a3-a9e8-7b5fd4e22ea9.png)
```
import latexify
from scipy.special import expit

@latexify.with_latex
def f(x):
    return expit(x)

f
```

**Comment by odashi** [comment]
@Vector-Cross Thanks for posting the issue.

We need more information about the expected behavior. I think this function could be expressed as different forms:

- $\sigma(x)$
- $\frac{1}{1 + \exp(-x)}$
- $\mathrm{expit}(x)$

either choice would be correct according to the situation.

**Comment by Vector-Cross** [comment]
> 

Thanks for reply. 
I wonder if there is a method that can be expressed in the second form.
Otherwise I have to redefinition sigmoid function by myself.

**Comment by odashi** [comment]
@Vector-Cross Great. At this point we have no options to expand composite functions, but we could provide something (namely `expand_functions` boolean option). It may be useful for other functions, e.g., `hypot` `atan2`. Let me work on this later.
