### ISSUE TITLE
Support expanding some functions

### ISSUE THREAD

**Issue by odashi** [google/latexify_py#65]
Follows #63 

It is good to provide a `expand_functions` boolean option to control whether some composite functions are expanded or not, e.g.:

- `hypot(x, y)` -> $\sqrt{x^2 + y^2}$
- `atan2(y, x)` -> $\arctan{\frac{y}{x}}$
- `expit(x)` -> $\frac{1}{1+\exp{(-x)}}$

**Comment by MAKMED1337** [comment]
Is it better `expit(x)` to be $\frac{1}{1+e^{-x}}$ ?

**Comment by odashi** [comment]
@MAKMED1337 Not sure, but it looks there should be another option to control the behavior around $\exp$ .

**Comment by ZibingZhang** [comment]
List of methods in `math` that I think we should allow expansion for:

- `exp(x)` -> $e^x$
- `exp2(x)` -> $2^x$
- `expm1(x)` -> $\exp(x) - 1$
- `log1p(x)` -> $\log(1 + x)$
- `pow(x, y)` -> $x^y$
- `atan2(x)` -> $\arctan(y / x)$
- `erf` -> too complicated, also I don't think integrals are supported... yet
- `erfc` -> see above
- `gamma` -> maybe for positive integers? I think it's best to leave alone for now
- `lgamma` -> see above

Let me know what you think @odashi, and I'll get started on these

**Comment by odashi** [comment]
I think non-elementary functions (`erf`, `erfc`, `gamma`, `lgamma`) should be avoided from this option. Other candidates looks fine to me.

**Comment by odashi** [comment]
I also think our current implementation (#125) naturally solves https://github.com/google/latexify_py/issues/65#issuecomment-1290288048 , as users can choose whether `exp` is expanded or not.

**Comment by odashi** [comment]
This is generally supported in the current implementation. We'd support individual functions in separate issues (if needed).
