### ISSUE TITLE
Multiple statements functions

### ISSUE THREAD

**Issue by odashi** [google/latexify_py#7]
Currently this tool analyses only the first statement of given functions, and passing multi-statement function results in generating garbages. Basically multiple statements are hard to interpret as a single equation and it is good not to support such things in the current `with_latex` and better to provide some other interfaces.

I am thinking of two things:

1. `latexify.array`/`latexify.eqnarray` for functions without control flow ... these may only contain the sequence of assignments/augmentations and we can represent them as equation arrays.
2. `latexify.algorithm` for general functions ... these are generally impossible to be written as simple equations, but we can output algorithmic form instead. Each statements can still be written by LaTeX formulas.

If we provide these functions, it is also good to rename `latexify.with_latex` to `latexify.equation` or some.

**Comment by yangc22** [comment]
Hi,
I have a question. When printing the function with the latexify decorator, is there any way that I can use the format string to print the string. As I have 10 functions name from "p1" to "p10". Is it possible to write a for loop to print all the functions?
Thanks.

**Comment by yangc22** [comment]
Also, is it possible to directly convert the function to string and write it to a file? Thanks!

**Comment by odashi** [comment]
@yangc22 Please create a new issue instead. Your question seems being not related to this topic.

**Comment by yangc22** [comment]
@odashi got it thanks!

**Comment by odashi** [comment]
Some comments has been moved to #14.

**Comment by yixingfu** [comment]
sorry I didn't see this discussion. I proposed a PR that interprets functions that has multiple statement that involves only simple assignment #24 . What do you think?

**Comment by odashi** [comment]
Close it for now. Composition of multiple statements is supported by #50
