### ISSUE TITLE
Some basic questions about this awesome project

### ISSUE THREAD

**Issue by moringspeaker** [google/latexify_py#75]
Hi, I accidentally found this project and it spends me quite a few time to basically figure out how this works and I'm still a little confused about it. Can I just simply summarize this Python package as a "decorator" which is used when we are writing a function in Python to generate an extra formula in Latex format?

**Comment by odashi** [comment]
@moringspeaker
Hi, thanks for asking your question!

First of all, the main branch is a bit different from the released version (v0.1.1). I'd like to explain how it works based on the main branch.

The core functionlity of this library is `latexify.frontend.get_latex()`. This function works as a "compiler" from Python functions to LaTeX with following steps:

1. Obtains the source code of the function: https://github.com/google/latexify_py/blob/c6c291d3bcce28a269d175be384ab955ac2100c8/src/latexify/parser.py#L25-L32
3. Obtains the parse tree of the source code: https://github.com/google/latexify_py/blob/c6c291d3bcce28a269d175be384ab955ac2100c8/src/latexify/parser.py#L34
4. Modifies the parse tree according to the config: https://github.com/google/latexify_py/blob/c6c291d3bcce28a269d175be384ab955ac2100c8/src/latexify/frontend.py#L51-L55
5. Generates LaTeX code corresponding to the modified parse tree: https://github.com/google/latexify_py/blob/c6c291d3bcce28a269d175be384ab955ac2100c8/src/latexify/frontend.py#L58-L62

`lateixfy.function` (formarly `latexify.with_latex`) is a function that converts the given function to another callable object that works similarly to the original function, but associated with the generated LaTeX code. This object can communicate with Jupyter to show the associated LaTeX expression (MathJax).

As for "decorator", the Python decorator is a syntax sugar to call the function with decorated stuff and replace the stuff with the return value. So the following two code are basically the same:

```python
@latexify.function
def f(x):
    ...
```
```python
def f(x):
    ...
f = latexify.function(f)
```

**Comment by moringspeaker** [comment]
Thanks for your patient explaination! I spent some time to read this awesome project's source code and I wonder if you guys plan to support some more complicated formats like a matrix or something?  It's always annoyed for me to write my own code to transfer a Numpy matrix into Latex format.

**Comment by odashi** [comment]
> support some more complicated formats like a matrix or something

Yeah sometimes it is requested, and particularly for arrays, I am still thinking of how/what range of expressions should be supported by this library (e.g., 2x2 arrays are small enough to compile, but large arrays and/or arrays with more than 2 dimensions are basically not suitable for LaTeX).

It would be nice to have a specific issue for arrays. Let me create it and continue discussion.

**Comment by odashi** [comment]
Delegated to #78.
