### ISSUE TITLE
NDArray support

### ISSUE THREAD

**Issue by odashi** [google/latexify_py#78]
Sometimes users want to support NDArrays in this library, e.g., `np.array([[a, b], [c, d]])` to 

$$\left( \begin{array}{cc}a&b \\\\ c&d\end{array} \right)$$

This is definitely useful, but often it is not possible to compile:

- Large arrays.
- Arrays with more than 2 dimensions.

I think we could start implementing it with reasonable restrictions (e.g., only NDArrays with <= 2 dimensions with small lengths), but it would be also good to keep discussion.

Refs:
- #38
- #53
- #75

**Comment by Casper-Guo** [comment]
For 2D arrays, limiting the maximum size to `10 x 10` is perhaps a reasonable starting point. Larger arrays, especially if they are dense, are not great as visual aids even if they are rendered into LaTex.

**Comment by moringspeaker** [comment]
> For 2D arrays, limiting the maximum size to `10 x 10` is perhaps a reasonable starting point. Larger arrays, especially if they are dense, are not great as visual aids even if they are rendered into LaTex.

I think it's a great idea to constraint the maximum size of matrices. I won't use matrix larger than 10 * 10 in Latex.

**Comment by odashi** [comment]
@Casper-Guo Yes I think it is reasonable. maybe we restrict to show only $(R, 1)$, $(1, C)$ and $(R, C)$ arrays with size $R \le R_{max}$ and $C \le C{max}$, where $R_{max}$ and $C_{max}$ is a config defaulted by some number (10 for example)

**Comment by Casper-Guo** [comment]
What should the configuration interface look like? I feel this should be file level rather than function level. 

@lakeblair

**Comment by odashi** [comment]
@Casper-Guo We can start with hard-coding the constraint into the code until we decided the structure of config files.

**Comment by kshxtij** [comment]
Is there a specific way, you'd suggest I implement this?

**Comment by Casper-Guo** [comment]
`np.eye`, `np.ones` and other matrix functions will probably be dealt with separately. I think the biggest issue with your current implementation is that it doesn’t generalize to 1D arrays / vectors
