### ISSUE TITLE
Fine-grained name processing

### ISSUE THREAD

**Issue by odashi** [google/latexify_py#82]
There are still some issues around name processing:

<img width="469" src="https://user-images.githubusercontent.com/1023695/200751324-1f0285cf-dc5a-4efa-b829-2545b1669c7a.png">

In the current implementation, only the function names are processed separately, but I think that that behavior is generally preferred for all identifiers, and it should be applied *by default*.

In some specific cases, it would be still good to process underscores (e.g., trailing numbers: `x_123` -> $x_{123}$), but rather this feature should be the option than retaining underscores.

**Comment by Casper-Guo** [comment]
The user should additionally be able to specify a list of variable names for which underscores are processed for each function. 

Or to make the feature easier to use, a list of variable names / variable prefixes for which underscores are processed can be specified at the beginning of the file

**Comment by odashi** [comment]
@Casper-Guo Yeah it would be good, but it may become a complicated config, and we need to focus on consolidating the name processing first (using the same processor for all function names, arguments, and identifiers in the body)

**Comment by odashi** [comment]
I guess this feature is really wanted by many users as far as I checked reactions in the social media. I would take my time to improve it.

**Comment by ZibingZhang** [comment]
> I guess this feature is really wanted by many users as far as I checked reactions in the social media. I would take my time to improve it.

Do you have a link to the post by any chance? Pretty sure I found this repo off of social media, but I can't seem to find the original post. Would be interesting to see other people's feedback and thoughts.

**Comment by odashi** [comment]
@ZibingZhang Sorry It's better not to share it here because the discussion I discovered involved a little offensive remarks.
Only I could say here is that some people hated the current behavior, and I really agreed it.

**Comment by odashi** [comment]
note: "many" is just my opinion, not guaranteed by any quantitive perspectives.

**Comment by adzcai** [comment]
Is there any way to recover the original behaviour and render the variable `x_3` with a subscript?
