### ISSUE TITLE
Wrong behavior around multiplication

### ISSUE THREAD

**Issue by odashi** [google/latexify_py#89]
The current implementation converts `a * b` into $ab$. This only works if the variables have only 1 character and doesn't generate a correct syntax for other cases:

* Long names: `abc * def` --> $abcdef$, which is hard to distinguish from other combination of variables.
* Unary operators: `x * -y` --> $x - y$, which is definitely wrong.

These cases require explicit multiply operator ( $\cdot$ or $\times$ ) between the operands.

I think the `Mult(left, right)` subtree should be converted to $left \cdot right$ *by default*, and try to avoid the operator only in the following cases:

- The left-hand side operand is a single character or a bracket (with or without unary operators and/or super/subscripts)
- The right-hand side operand is a single character or a bracket (with or without super/subscripts, *without* unary operators)

This requires fine-graind name processing, and may be applied after #82.

**Comment by odashi** [comment]
Anyway, I will handle this issue today.

**Comment by odashi** [comment]
Anyway some simple heuristic can be applied without waiting for #82

**Comment by odashi** [comment]
Re-open this issue since it is actually not resolved yet.

**Comment by odashi** [comment]
Maybe it's good if we get a list of possible LHS-RHS pairs with/without the multiplication symbol, e.g.,

| left | right | tex |
| ---- | ----- | ------ |
| `3` | `x` | $3 x$ |
| `x` | `y` | $x \cdot y$ |

**Comment by ZibingZhang** [comment]
I can't think of a case where we would want to remove the `\cdot` other than the case of `constant * name`.

| left | right | tex | why |
| --- | --- | --- | --- |
| `3` | `x` | $3x$ | basic multiplication with constant (should work with floats and complex) |
| `x` | `3` | $x \cdot 3$ | should not reorder for user, if they want lack of `\cdot`, can change order themselves |
| `two`| `names` | $two \cdot names$ | two variables should always have a `\cdot` |
| `3` | `x * 4 * y` | $3x \cdot 4y$ | should work in more complicated expression as well |

**Comment by odashi** [comment]
Some complete examples:

| | numeric | alphabet | math | word | function | bracket |
|-|-|-|-|-|-|-|
| numeric | $2 \cdot 3$ | $\color{red} 2 y$ | $\color{red} 2 \beta$ | $2 \cdot \mathrm{bar}$ | $2 \cdot g(y)$ | $\color{red} 2 (u + v)$ |
| alphabet | $x \cdot 3$ | $\color{red} x y$ | $\color{red} x \beta$ | $x \cdot \mathrm{bar}$ | $x \cdot g(y)$ | $x \cdot (u + v)$ |
| math | $\alpha \cdot 3$ | $\color{red} \alpha y$ | $\color{red} \alpha \beta$ | $\alpha \cdot \mathrm{bar}$ | $\alpha \cdot g(y)$ | $\alpha \cdot (u + v)$ |
| word | $\mathrm{foo} \cdot 3$ | $\mathrm{foo} \cdot x$ | $\mathrm{foo} \cdot \beta$ | $\mathrm{foo} \cdot \mathrm{bar}$ | $\mathrm{foo} \cdot g(y)$ | $\mathrm{foo} \cdot (u + v)$ |
| function | $f(x) \cdot 3$ | $f(x) \cdot y$ | $f(x) \cdot \beta$ | $f(x) \cdot \mathrm{bar}$ | $f(x) \cdot g(y)$ | $\color{red} f(x) (u + v)$ |
| bracket | $(s + t) \cdot 3$ | $(s + t) \cdot y$ | $(s + t) \cdot \beta$ | $(s + t) \cdot \mathrm{bar}$ | $(s + t) \cdot g(y)$ | $\color{red} (s + t) (u + v)$ |

**Comment by ZibingZhang** [comment]
I think `alphabet-alphabet` would also cause confusion, because you could have a (arguably dumb) case like

```python
def (x, y, xy):
    return xy
```

In general though when user sees $xy$ there's no easy way of telling if it's $x \cdot y$ or a single variable $xy$, so I think it we should keep the `\cdot`.

**Comment by odashi** [comment]
> I'm realizing that word is stylized differently than alphabet

Yes this is intended in #139, but maybe the result is somewhat confusing for some users.

**Comment by ZibingZhang** [comment]
Looking through the code this seems like we'll have to utilize information from expr codegen to figure out what nodes are wrapped in parens, as well as information from identifier replacer to differentiate between math vs. alphabet vs. word.

**Comment by ZibingZhang** [comment]
Another situation, if we have `a * b @ x @ y`, this should result in $ab \cdot xy$.

**Comment by odashi** [comment]
> Another situation, if we have a * b @ x @ y, this should result in .

It looks $abxy$ is acceptable. $ab \cdot xy$ looks to represent `(a*b)@(x@y)`, but:

* Matrix multiplication is an associative operation: position of parenthesis is meaningless
* We get the AST `(((a*b)@x)@y)` for this expression.

**Comment by odashi** [comment]
I think we eventually need more informative object than the raw string for expression codegen to implement this feature (and other stuff that rely on the LaTeX syntax rules). let me implement it later
